### ISSUE TITLE
Change settings depending on what GitHub Actions runs

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#203]
これ並列でテスト回せなくなりませんか（verifyとsantizeみたいなのどうすれば実現できますか　https://github.com/beet-aizu/library/actions

_Originally posted by @beet-aizu in https://github.com/kmyk/online-judge-verify-helper/pull/200#issuecomment-599827906_

---

解決策の方向性はおそらく 3 通り:

1. 環境変数を読む
2. `config.toml` に機能を加える
3. オプションで `config.toml` を指定

(1.) はこれまで利用されていたもので、誤爆等の問題があるため適切でない。
(2.) は例えば

``` toml
[[languages.cpp.environments]]
CXXFLAGS = ${CXXFLAGS}
```

とか

``` toml
[[enable_if]]
    a = "GITHUB_HOGE"
    op = "equals"
    b = "sanitize.yml"
    [body]
        [[languages.cpp.environments]]
        CXXFLAGS = ${CXXFLAGS}
```

とか書けるようにする感じになりそう。明らかに闇なのでやりたくない。

(3.) がたぶん最もまとも。`sanitize.yml` では以下のように書くとかする。

``` yaml
    - name: Run tests
      run: oj-verify --config-file .verify-helper/sanitize-config.toml run
```
