### ISSUE TITLE
sanitizeのときだけIGNOREしたかったのがこわれている

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#205]
https://github.com/kmyk/online-judge-verify-helper/blob/ad6d07479e22865661030ec49ea4f8f707083dc1/onlinejudge_verify/languages/cplusplus.py#L153

**Comment by beet-aizu** [comment]
これ何がしたかったんだろうな（は？）

**Comment by beet-aizu** [comment]
直ってないです

**Comment by kmyk** [comment]
@beet-aizu 「sanitize のときだけ IGNORE」って元々どうやって実現していましたか？

**Comment by beet-aizu** [comment]
https://beet-aizu.github.io/library/verify/test/yosupo/persistent_queue.test.cpp.html　前はこれで動いていました

**Comment by kmyk** [comment]
``` toml
[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++17", "-Wall", "-g", "-DSANITIZE", "-fsanitize=undefined", "-D_GLIBCXX_DEBUG"]
```

かつ

``` c++
#ifdef SANITIZE
#define IGNORE
#endif
```

なら動くように書いたはずなんですが、動いてないということはバグです。
