### ISSUE TITLE
多言語対応

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#73]
Python, Rust, C#, D, Java, F#, Haskell の人などがおり、おそらく望まれています。
あと、このまま放置すると C++ に強依存した機能を追加したくなってしまって面倒なので、引き返せなくなる前に早めに多言語対応しておきたい。ただし雑に対応すると「じゃあこの言語も対応してくれ」の要望がたくさん来てつらいのでうまく一般的な枠組みを用意する必要があります。

## 仕様案 1

`.verify-helper/config.toml` みたいなところにたとえば以下のような雰囲気でコマンドを書いておく。

``` toml
[ext.".py"]
compile = "python3 -m compileall {}"
execute = "PYTHONPATH={} python3 {}"
list_attributes = "sed 's/#define // ; t ; d'"
list_dependencies = "./hoge.sh"
bundle = "./fuga.sh"

[ext.".cs"]
compile = "..."
execute = "..."
list_attributes = "..."
list_dependencies = "..."
bundle = "..."
```
